### ISSUE TITLE
Error When Following Development Guide

### ISSUE THREAD

**Issue by henryteng07** [catamphetamine/anychan#13]
I completed the initial setup but I am facing an issue when I run "yarn run dev". 

<img width="598" alt="Screenshot 2023-04-21 at 5 02 21 pm" src="https://user-images.githubusercontent.com/61112534/233614717-18649940-2f12-4c3f-b48d-c52ee72dc212.png">

Could you please advise me on how I can solve this?

**Comment by catamphetamine** [comment]
Hmm, I'll look.

**Comment by henryteng07** [comment]
Thank you so much!

**Comment by henryteng07** [comment]
According to ChatGPT. Hope it helps :D 
<img width="924" alt="Screenshot 2023-04-21 at 5 25 29 pm" src="https://user-images.githubusercontent.com/61112534/233619201-75657940-5215-4149-a2e0-27f617bbaad9.png">

**Comment by catamphetamine** [comment]
Pull the latest code and run `yarn`.

Seems to be fixed.

**Comment by henryteng07** [comment]
Tysm! Its fixed now
