### ISSUE TITLE
/adv board doesn't show images

### ISSUE THREAD

**Issue by b-lov** [catamphetamine/anychan#14]
<img width="1285" alt="Screenshot 2023-09-05 at 19 33 19" src="https://github.com/catamphetamine/anychan/assets/8249085/9948103e-691c-415e-9d30-b8c2d33d346d">

only happens on 4chan/adv, all other boards display images fine.

**Comment by catamphetamine** [comment]
Hi.

This looks to be an issue with `uBlock` chrome extension.

With `uBlock` enabled:

![image](https://github.com/catamphetamine/anychan/assets/477167/73d16ae3-b122-4d92-b332-e25d49e438cb)

With `uBlock` disabled:

![image](https://github.com/catamphetamine/anychan/assets/477167/7432443b-9e52-4096-9840-e8f33e3c493b)

You can report it to `uBlock`, I guess.

**Comment by b-lov** [comment]
how could i not have thought of this 🙈
i guess i was distracted by the fact that it happened only on that one specific board...
anyway, thanks for your help!
